global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'quarkus'
    scrape_interval: 5s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['192.168.0.13:8080']
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']  
